import Products from '@/components/products/Products';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Product page",
  description: "Generated by create next app",
};

const Product = async () => {
    const data = await fetch("https://dummyjson.com/products?limit=12", { cache: "force-cache" });
    const products = await data.json();
  return (
    <div>
        <Products data={products} />
    </div>
  )
}

export default Product