import { Metadata } from "next";
import Product from "./product/page";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function  Home() {
  
  
  return (
    <div>
      <Product/>
    </div>
  );
}
