import Products from "@/components/products/Products";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function  Home() {
  const data = await fetch("https://dummyjson.com/products?limit=12", { cache: "no-store" });
  const products = await data.json();
  console.log(products);
  
  return (
    <div>
      <Products data={products}/>
    </div>
  );
}
