import { Metadata } from "next";
import React from "react";
import User from "@/components/user/User";

export const metadata: Metadata = {
  title: "User page",
  description: "Generated by create next app",
};

const UserPage = async () => {
  const data = await fetch("https://dummyjson.com/users?limit=12", { cache: "force-cache" });
  const users = await data.json();
  return (
    <div>
      <User data={users} />
    </div>
  );
};

export default UserPage;
