import Recipes from "@/components/recipe/Recipes";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Recipe page",
  description: "Generated by create next app",
};

const RecipePage = async () => {
  const data = await fetch("https://dummyjson.com/recipes?limit=12", { cache: "force-cache" });
  const recipes = await data.json();

  return <div>
      <Recipes data={recipes}/>
      </div>;
};

export default RecipePage;
