import React from 'react'
import Post from "@/components/post/Post";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Post page",
  description: "Generated by create next app",
};

const PostPage = async () => {
  const data = await fetch("https://dummyjson.com/posts?limit=12", { cache: "force-cache" });
  const posts = await data.json();

  return (
    <div>
      <Post data={posts} />
    </div>
  );
};

export default PostPage;
